### ISSUE TITLE
Fails to launch on RS-90

### ISSUE THREAD

**Issue by Cralex** [glebm/rs97-commander#9]
Hello, 
I downloaded the new opk for RS-90 released 4/4, placed it with my other opks on the internal storage, and rebooted my device. Commander appeared in the menu, but attempting to launch it caused gmenu to pause for a moment and then stop trying to launch it. The log file it generated says:

Error relocating commander: _stat_time64: symbol not found
Error relocating commander:_lstat_time64: symbol not found

My firmware is kernel 5.5.0-rc5+
Compiled: Mon Jan 6 2020
Rootfs: g23cc08145a
Compiled: Tue Jan 7 2020

Let me know if there’s anything I can do to help debug this. Thanks!

**Comment by glebm** [comment]
I've built the OPK with the latest buildroot instead of the 2019.04 toolchain and that wasn't compatible with the current firmware release

Re-built with the toolchain from https://zcrc.me/retromini/2019/04/30/opendingux-release-20190430.html and re-uploaded the OPK at https://github.com/glebm/od-commander/releases/download/2020-04-04/commander-rs90.opk
